syntax = "proto3";

option csharp_namespace = "IDCC.Cache.Grpc";

service PeerService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc Set(SetRequest) returns (SetResponse);
  rpc Remove(RemoveRequest) returns (RemoveResponse);
}

message GetRequest {
  string key = 1;
}

message GetResponse {
  bytes value = 1;
  
  // Client version of the cache item
  int64 version = 2;
}

message SetRequest {
  string key = 1;
  
  bytes value = 2;

  // Client version of the cache item
  int64 version = 3;

  // Optional time to live in seconds from now
  optional int32 ttl_seconds = 4;
}

message SetResponse {
}

message RemoveRequest {
  string key = 1;

  // Client version of the cache item
  int64 version = 2;
}

message RemoveResponse {
}
